# Generated by Django 4.0.1 on 2022-01-31 12:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_message'),
    ]

    operations = [
        migrations.RenameField(
            model_name='message',
            old_name='recipeint',
            new_name='recipient',
        ),
    ]
