# Generated by Django 4.0.1 on 2022-01-31 12:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_rename_recipeint_message_recipient'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='profile',
            options={'ordering': ['created']},
        ),
    ]
